export const INDUSTRIES = [
  {
    slug: "private-equity",
    name: "Private Equity",
    description: "AI solutions for PE firms and portfolio companies",
    keywords: ["portfolio optimization", "due diligence", "value creation", "AI transformation"],
    challenges: [
      "Portfolio company digital transformation",
      "AI due diligence and assessment",
      "Value creation through automation",
      "Competitive advantage through AI",
      "Exit value maximization",
    ],
    solutions: [
      "Portfolio-wide AI assessment",
      "Rapid AI implementation sprints",
      "Custom AI development",
      "Team training and enablement",
      "AI strategy consulting",
    ],
    metrics: {
      avgROI: "3.5x",
      timeToValue: "60 days",
      portfolioImpact: "25% efficiency gain",
    },
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    description: "Medical AI and healthcare automation solutions",
    keywords: ["medical AI", "clinical automation", "patient care", "healthcare analytics"],
    challenges: [
      "Clinical decision support",
      "Patient data management",
      "Administrative automation",
      "Diagnostic assistance",
      "Regulatory compliance",
    ],
    solutions: [
      "Clinical AI assistants",
      "Medical imaging analysis",
      "Patient flow optimization",
      "Documentation automation",
      "Predictive health analytics",
    ],
    metrics: {
      avgROI: "2.8x",
      timeToValue: "90 days",
      efficiencyGain: "40% time savings",
    },
  },
  {
    slug: "financial-services",
    name: "Financial Services",
    description: "AI for banking, insurance, and fintech",
    keywords: ["fintech AI", "banking automation", "risk analysis", "fraud detection"],
    challenges: [
      "Fraud detection and prevention",
      "Risk assessment automation",
      "Customer service scaling",
      "Regulatory compliance",
      "Investment analysis",
    ],
    solutions: [
      "Fraud detection systems",
      "Automated underwriting",
      "Customer service AI",
      "Compliance automation",
      "Trading algorithms",
    ],
    metrics: {
      avgROI: "4.2x",
      timeToValue: "45 days",
      fraudReduction: "65%",
    },
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    description: "Smart factory and industrial AI solutions",
    keywords: ["smart factory", "predictive maintenance", "quality control", "supply chain AI"],
    challenges: [
      "Predictive maintenance needs",
      "Quality control automation",
      "Supply chain optimization",
      "Production planning",
      "Worker safety",
    ],
    solutions: [
      "Predictive maintenance AI",
      "Computer vision QC",
      "Supply chain optimization",
      "Production scheduling AI",
      "Safety monitoring systems",
    ],
    metrics: {
      avgROI: "3.2x",
      timeToValue: "75 days",
      downtimeReduction: "45%",
    },
  },
  {
    slug: "retail",
    name: "Retail & E-commerce",
    description: "AI for retail and online commerce",
    keywords: ["retail AI", "e-commerce automation", "personalization", "inventory optimization"],
    challenges: [
      "Customer personalization",
      "Inventory management",
      "Demand forecasting",
      "Customer service scaling",
      "Pricing optimization",
    ],
    solutions: [
      "Recommendation engines",
      "Inventory optimization AI",
      "Demand forecasting",
      "Chatbot assistants",
      "Dynamic pricing AI",
    ],
    metrics: {
      avgROI: "2.5x",
      timeToValue: "30 days",
      conversionIncrease: "35%",
    },
  },
  {
    slug: "saas",
    name: "SaaS & Technology",
    description: "AI for software and technology companies",
    keywords: ["SaaS AI", "product analytics", "customer success", "developer tools"],
    challenges: [
      "User behavior analytics",
      "Customer churn prediction",
      "Product feature optimization",
      "Support automation",
      "Development acceleration",
    ],
    solutions: [
      "User analytics AI",
      "Churn prediction models",
      "Feature recommendation",
      "Support automation",
      "Code generation tools",
    ],
    metrics: {
      avgROI: "3.8x",
      timeToValue: "21 days",
      churnReduction: "30%",
    },
  },
  {
    slug: "legal",
    name: "Legal Services",
    description: "AI for law firms and legal departments",
    keywords: ["legal AI", "contract analysis", "document review", "legal research"],
    challenges: [
      "Document review efficiency",
      "Contract analysis",
      "Legal research",
      "Case prediction",
      "Billing optimization",
    ],
    solutions: [
      "Document review AI",
      "Contract analysis tools",
      "Legal research AI",
      "Case outcome prediction",
      "Time tracking automation",
    ],
    metrics: {
      avgROI: "2.9x",
      timeToValue: "60 days",
      reviewTimeReduction: "70%",
    },
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    description: "AI for property and real estate businesses",
    keywords: ["proptech AI", "property valuation", "market analysis", "tenant screening"],
    challenges: [
      "Property valuation accuracy",
      "Market trend analysis",
      "Tenant screening",
      "Maintenance prediction",
      "Lead generation",
    ],
    solutions: [
      "Valuation AI models",
      "Market analysis tools",
      "Tenant screening AI",
      "Predictive maintenance",
      "Lead scoring systems",
    ],
    metrics: {
      avgROI: "2.7x",
      timeToValue: "45 days",
      valuationAccuracy: "95%",
    },
  },
  {
    slug: "education",
    name: "Education",
    description: "AI for educational institutions and EdTech",
    keywords: ["EdTech AI", "personalized learning", "student analytics", "curriculum optimization"],
    challenges: [
      "Personalized learning paths",
      "Student performance prediction",
      "Content generation",
      "Administrative automation",
      "Engagement tracking",
    ],
    solutions: [
      "Adaptive learning AI",
      "Performance analytics",
      "Content generation tools",
      "Admin automation",
      "Engagement analytics",
    ],
    metrics: {
      avgROI: "2.3x",
      timeToValue: "90 days",
      engagementIncrease: "40%",
    },
  },
  {
    slug: "logistics",
    name: "Logistics & Supply Chain",
    description: "AI for logistics and supply chain management",
    keywords: ["logistics AI", "route optimization", "warehouse automation", "demand planning"],
    challenges: [
      "Route optimization",
      "Warehouse efficiency",
      "Demand forecasting",
      "Fleet management",
      "Last-mile delivery",
    ],
    solutions: [
      "Route optimization AI",
      "Warehouse automation",
      "Demand planning AI",
      "Fleet analytics",
      "Delivery optimization",
    ],
    metrics: {
      avgROI: "3.6x",
      timeToValue: "60 days",
      costReduction: "25%",
    },
  },
];

export type Industry = typeof INDUSTRIES[0];