export const INDUSTRIES = [
  {
    slug: "private-equity",
    name: "Private Equity",
    description: "Document intelligence and AI automation for PE firms and portfolio companies",
    keywords: ["portfolio optimization", "due diligence", "value creation", "AI transformation", "document intelligence", "PDF extraction"],
    challenges: [
      "Portfolio company digital transformation",
      "AI due diligence and assessment",
      "Value creation through automation",
      "Competitive advantage through AI",
      "Exit value maximization",
    ],
    solutions: [
      "Portfolio-wide AI assessment",
      "Rapid AI implementation sprints",
      "Custom AI development",
      "Team training and enablement",
      "AI strategy consulting",
    ],
    documentTypes: [
      "Investment memos & deal documents",
      "Portfolio company financials",
      "Due diligence reports",
      "LP reports & communications",
      "Board decks & presentations",
      "Legal agreements & contracts",
    ],
    automationOpportunities: [
      "Automated deal screening & scoring",
      "Portfolio company KPI extraction",
      "LP report generation",
      "Due diligence document analysis",
      "Investment memo creation",
    ],
    metrics: {
      avgROI: "3.5x",
      timeToValue: "60 days",
      portfolioImpact: "25% efficiency gain",
      documentProcessing: "≥60% touchless",
    },
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    description: "Medical document intelligence and clinical automation solutions",
    keywords: ["medical AI", "clinical automation", "patient care", "healthcare analytics", "medical records", "HIPAA compliant"],
    challenges: [
      "Clinical decision support",
      "Patient data management",
      "Administrative automation",
      "Diagnostic assistance",
      "Regulatory compliance",
    ],
    solutions: [
      "Clinical AI assistants",
      "Medical imaging analysis",
      "Patient flow optimization",
      "Documentation automation",
      "Predictive health analytics",
    ],
    documentTypes: [
      "Electronic health records (EHR)",
      "Insurance claims & EOBs",
      "Clinical notes & reports",
      "Prior authorizations",
      "Lab results & imaging reports",
      "Patient intake forms",
    ],
    automationOpportunities: [
      "Medical coding automation",
      "Prior auth processing",
      "Claims adjudication",
      "Clinical documentation improvement",
      "Patient record summarization",
    ],
    metrics: {
      avgROI: "2.8x",
      timeToValue: "90 days",
      efficiencyGain: "40% time savings",
      documentProcessing: "70% automation rate",
    },
  },
  {
    slug: "financial-services",
    name: "Financial Services",
    description: "Document intelligence for banking, insurance, and fintech operations",
    keywords: ["fintech AI", "banking automation", "risk analysis", "fraud detection", "KYC automation", "loan processing"],
    challenges: [
      "Fraud detection and prevention",
      "Risk assessment automation",
      "Customer service scaling",
      "Regulatory compliance",
      "Investment analysis",
    ],
    solutions: [
      "Fraud detection systems",
      "Automated underwriting",
      "Customer service AI",
      "Compliance automation",
      "Trading algorithms",
    ],
    documentTypes: [
      "Loan applications & underwriting docs",
      "KYC/AML documentation",
      "Financial statements & tax returns",
      "Insurance policies & claims",
      "Trade confirmations & settlements",
      "Regulatory filings & reports",
    ],
    automationOpportunities: [
      "Automated loan underwriting",
      "KYC document verification",
      "Financial statement analysis",
      "Claims processing automation",
      "Regulatory reporting extraction",
    ],
    metrics: {
      avgROI: "4.2x",
      timeToValue: "45 days",
      fraudReduction: "65%",
      documentProcessing: "80% straight-through",
    },
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    description: "Smart factory automation and industrial document processing",
    keywords: ["smart factory", "predictive maintenance", "quality control", "supply chain AI", "production documents", "compliance automation"],
    challenges: [
      "Predictive maintenance needs",
      "Quality control automation",
      "Supply chain optimization",
      "Production planning",
      "Worker safety",
    ],
    solutions: [
      "Predictive maintenance AI",
      "Computer vision QC",
      "Supply chain optimization",
      "Production scheduling AI",
      "Safety monitoring systems",
    ],
    documentTypes: [
      "Purchase orders & invoices",
      "Bills of materials (BOMs)",
      "Quality inspection reports",
      "Shipping & receiving documents",
      "Compliance certifications",
      "Equipment maintenance logs",
    ],
    automationOpportunities: [
      "PO to invoice matching",
      "BOM data extraction",
      "Quality report analysis",
      "Compliance tracking automation",
      "Maintenance schedule optimization",
    ],
    metrics: {
      avgROI: "3.2x",
      timeToValue: "75 days",
      downtimeReduction: "45%",
      documentProcessing: "65% automation",
    },
  },
  {
    slug: "retail",
    name: "Retail & E-commerce",
    description: "Document automation and AI for retail operations",
    keywords: ["retail AI", "e-commerce automation", "personalization", "inventory optimization", "vendor documents", "order processing"],
    challenges: [
      "Customer personalization",
      "Inventory management",
      "Demand forecasting",
      "Customer service scaling",
      "Pricing optimization",
    ],
    solutions: [
      "Recommendation engines",
      "Inventory optimization AI",
      "Demand forecasting",
      "Chatbot assistants",
      "Dynamic pricing AI",
    ],
    documentTypes: [
      "Purchase orders & vendor invoices",
      "Product catalogs & spec sheets",
      "Return merchandise authorizations",
      "Shipping manifests & BOLs",
      "Customer orders & receipts",
      "Vendor agreements & contracts",
    ],
    automationOpportunities: [
      "Vendor invoice processing",
      "Product catalog ingestion",
      "Return processing automation",
      "Order fulfillment tracking",
      "Contract data extraction",
    ],
    metrics: {
      avgROI: "2.5x",
      timeToValue: "30 days",
      conversionIncrease: "35%",
      documentProcessing: "75% automation",
    },
  },
  {
    slug: "saas",
    name: "SaaS & Technology",
    description: "AI automation for software companies and tech operations",
    keywords: ["SaaS AI", "product analytics", "customer success", "developer tools", "contract automation", "support documentation"],
    challenges: [
      "User behavior analytics",
      "Customer churn prediction",
      "Product feature optimization",
      "Support automation",
      "Development acceleration",
    ],
    solutions: [
      "User analytics AI",
      "Churn prediction models",
      "Feature recommendation",
      "Support automation",
      "Code generation tools",
    ],
    documentTypes: [
      "Customer contracts & MSAs",
      "Support tickets & documentation",
      "Product requirements docs",
      "API documentation",
      "User feedback & surveys",
      "Security questionnaires",
    ],
    automationOpportunities: [
      "Contract analysis & renewal tracking",
      "Support ticket classification",
      "Requirements extraction",
      "Documentation generation",
      "Security questionnaire completion",
    ],
    metrics: {
      avgROI: "3.8x",
      timeToValue: "21 days",
      churnReduction: "30%",
      documentProcessing: "85% automation",
    },
  },
  {
    slug: "legal",
    name: "Legal Services",
    description: "Document intelligence for law firms and legal departments",
    keywords: ["legal AI", "contract analysis", "document review", "legal research", "due diligence", "M&A documents"],
    challenges: [
      "Document review efficiency",
      "Contract analysis",
      "Legal research",
      "Case prediction",
      "Billing optimization",
    ],
    solutions: [
      "Document review AI",
      "Contract analysis tools",
      "Legal research AI",
      "Case outcome prediction",
      "Time tracking automation",
    ],
    documentTypes: [
      "Contracts & agreements",
      "Discovery documents",
      "Due diligence materials",
      "Legal briefs & memos",
      "Court filings & pleadings",
      "M&A transaction documents",
    ],
    automationOpportunities: [
      "Contract clause extraction",
      "Due diligence review automation",
      "Discovery document classification",
      "Legal research summarization",
      "M&A document analysis",
    ],
    metrics: {
      avgROI: "2.9x",
      timeToValue: "60 days",
      reviewTimeReduction: "70%",
      documentProcessing: "90% accuracy",
    },
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    description: "Document automation for property and real estate operations",
    keywords: ["proptech AI", "property valuation", "market analysis", "tenant screening", "lease processing", "property documents"],
    challenges: [
      "Property valuation accuracy",
      "Market trend analysis",
      "Tenant screening",
      "Maintenance prediction",
      "Lead generation",
    ],
    solutions: [
      "Valuation AI models",
      "Market analysis tools",
      "Tenant screening AI",
      "Predictive maintenance",
      "Lead scoring systems",
    ],
    documentTypes: [
      "Lease agreements & addendums",
      "Property listings & MLS data",
      "Title documents & deeds",
      "Inspection reports",
      "Tenant applications & screening",
      "Property management agreements",
    ],
    automationOpportunities: [
      "Lease data extraction",
      "MLS listing ingestion",
      "Title document analysis",
      "Inspection report processing",
      "Tenant application screening",
    ],
    metrics: {
      avgROI: "2.7x",
      timeToValue: "45 days",
      valuationAccuracy: "95%",
      documentProcessing: "70% automation",
    },
  },
  {
    slug: "education",
    name: "Education",
    description: "AI automation for educational institutions and EdTech",
    keywords: ["EdTech AI", "personalized learning", "student analytics", "curriculum optimization", "transcript processing", "admissions automation"],
    challenges: [
      "Personalized learning paths",
      "Student performance prediction",
      "Content generation",
      "Administrative automation",
      "Engagement tracking",
    ],
    solutions: [
      "Adaptive learning AI",
      "Performance analytics",
      "Content generation tools",
      "Admin automation",
      "Engagement analytics",
    ],
    documentTypes: [
      "Student transcripts & records",
      "Admissions applications",
      "Course materials & syllabi",
      "Assessment & test papers",
      "Financial aid documents",
      "Accreditation reports",
    ],
    automationOpportunities: [
      "Transcript evaluation automation",
      "Application processing & screening",
      "Course material digitization",
      "Assessment grading automation",
      "Financial aid verification",
    ],
    metrics: {
      avgROI: "2.3x",
      timeToValue: "90 days",
      engagementIncrease: "40%",
      documentProcessing: "60% automation",
    },
  },
  {
    slug: "logistics",
    name: "Logistics & Supply Chain",
    description: "Document intelligence for logistics and 3PL operations",
    keywords: ["logistics AI", "route optimization", "warehouse automation", "demand planning", "BOL processing", "freight documents"],
    challenges: [
      "Route optimization",
      "Warehouse efficiency",
      "Demand forecasting",
      "Fleet management",
      "Last-mile delivery",
    ],
    solutions: [
      "Route optimization AI",
      "Warehouse automation",
      "Demand planning AI",
      "Fleet analytics",
      "Delivery optimization",
    ],
    documentTypes: [
      "Bills of lading (BOLs)",
      "Freight invoices & quotes",
      "Proof of delivery (PODs)",
      "Customs & import/export docs",
      "Rate confirmations",
      "Warehouse receipts & manifests",
    ],
    automationOpportunities: [
      "BOL data extraction & matching",
      "Freight audit & payment",
      "POD verification automation",
      "Customs document processing",
      "Rate quote analysis",
    ],
    metrics: {
      avgROI: "3.6x",
      timeToValue: "60 days",
      costReduction: "25%",
      documentProcessing: "80% touchless",
    },
  },
];

export type Industry = typeof INDUSTRIES[0];

export interface DocumentIntelligence {
  documentTypes: string[];
  automationOpportunities: string[];
}