export const PROBLEMS = [
  {
    slug: "customer-service",
    name: "Customer Service Automation",
    description: "Scale support without scaling headcount",
    painPoints: [
      "High support ticket volume",
      "Repetitive inquiries",
      "Long response times",
      "24/7 coverage needs",
      "Multi-language support",
    ],
    aiCapabilities: ["Natural Language Processing", "Conversational AI", "Sentiment Analysis"],
    solutions: ["Chatbots", "Virtual Assistants", "Ticket Routing", "Response Automation"],
    metrics: {
      ticketReduction: "60%",
      responseTime: "90% faster",
      satisfaction: "+25% CSAT",
    },
  },
  {
    slug: "data-analysis",
    name: "Data Analysis & Insights",
    description: "Transform data into actionable intelligence",
    painPoints: [
      "Data silos",
      "Manual reporting",
      "Delayed insights",
      "Complex data sources",
      "Missing patterns",
    ],
    aiCapabilities: ["Machine Learning", "Predictive Analytics", "Pattern Recognition"],
    solutions: ["Analytics Dashboards", "Predictive Models", "Automated Reporting", "Anomaly Detection"],
    metrics: {
      analysisSpeed: "10x faster",
      accuracy: "95%",
      insightDiscovery: "+40%",
    },
  },
  {
    slug: "document-processing",
    name: "Document Processing",
    description: "Automate document handling and extraction",
    painPoints: [
      "Manual data entry",
      "Processing delays",
      "Error-prone extraction",
      "Compliance risks",
      "Storage inefficiency",
    ],
    aiCapabilities: ["OCR", "NLP", "Computer Vision", "Information Extraction"],
    solutions: ["Document Intelligence", "Form Processing", "Contract Analysis", "Invoice Automation"],
    metrics: {
      processingTime: "85% reduction",
      accuracy: "99.5%",
      costSavings: "70%",
    },
  },
  {
    slug: "quality-control",
    name: "Quality Control",
    description: "Automated quality assurance and defect detection",
    painPoints: [
      "Manual inspection",
      "Inconsistent standards",
      "Late defect detection",
      "Sampling limitations",
      "Training costs",
    ],
    aiCapabilities: ["Computer Vision", "Anomaly Detection", "Pattern Recognition"],
    solutions: ["Visual Inspection AI", "Defect Detection", "Quality Prediction", "Process Monitoring"],
    metrics: {
      defectDetection: "99%",
      inspectionSpeed: "20x",
      falsePositives: "<1%",
    },
  },
  {
    slug: "fraud-detection",
    name: "Fraud Detection",
    description: "Identify and prevent fraudulent activities",
    painPoints: [
      "Evolving fraud patterns",
      "False positives",
      "Real-time detection needs",
      "Investigation time",
      "Financial losses",
    ],
    aiCapabilities: ["Anomaly Detection", "Pattern Recognition", "Real-time Analytics"],
    solutions: ["Transaction Monitoring", "Risk Scoring", "Behavioral Analysis", "Alert Systems"],
    metrics: {
      fraudPrevention: "65%",
      falsePositives: "-50%",
      detectionSpeed: "Real-time",
    },
  },
  {
    slug: "personalization",
    name: "Personalization",
    description: "Deliver tailored experiences at scale",
    painPoints: [
      "Generic experiences",
      "Low engagement",
      "Manual segmentation",
      "Content relevance",
      "Scale limitations",
    ],
    aiCapabilities: ["Recommendation Engines", "Behavioral Analysis", "Predictive Modeling"],
    solutions: ["Content Personalization", "Product Recommendations", "Dynamic Pricing", "Email Targeting"],
    metrics: {
      engagement: "+45%",
      conversion: "+35%",
      retention: "+30%",
    },
  },
  {
    slug: "predictive-maintenance",
    name: "Predictive Maintenance",
    description: "Prevent failures before they happen",
    painPoints: [
      "Unexpected downtime",
      "Maintenance costs",
      "Equipment failures",
      "Scheduling inefficiency",
      "Part inventory",
    ],
    aiCapabilities: ["Time Series Analysis", "Anomaly Detection", "Predictive Modeling"],
    solutions: ["Failure Prediction", "Maintenance Scheduling", "Sensor Analytics", "Part Optimization"],
    metrics: {
      downtimeReduction: "50%",
      maintenanceCost: "-30%",
      equipmentLife: "+20%",
    },
  },
  {
    slug: "supply-chain",
    name: "Supply Chain Optimization",
    description: "Optimize inventory and logistics",
    painPoints: [
      "Demand variability",
      "Inventory costs",
      "Supply disruptions",
      "Route inefficiency",
      "Visibility gaps",
    ],
    aiCapabilities: ["Optimization Algorithms", "Demand Forecasting", "Route Planning"],
    solutions: ["Demand Planning", "Inventory Optimization", "Route Optimization", "Risk Management"],
    metrics: {
      inventoryCost: "-25%",
      stockouts: "-40%",
      deliveryTime: "-20%",
    },
  },
  {
    slug: "content-generation",
    name: "Content Generation",
    description: "Create content at scale with AI",
    painPoints: [
      "Content volume needs",
      "Creation time",
      "Consistency issues",
      "Translation needs",
      "SEO optimization",
    ],
    aiCapabilities: ["Natural Language Generation", "GPT Models", "Translation AI"],
    solutions: ["Blog Generation", "Product Descriptions", "Social Media Content", "Email Templates"],
    metrics: {
      contentOutput: "10x",
      creationTime: "-80%",
      engagement: "+30%",
    },
  },
  {
    slug: "risk-assessment",
    name: "Risk Assessment",
    description: "Automate risk evaluation and scoring",
    painPoints: [
      "Manual assessment",
      "Inconsistent scoring",
      "Slow processing",
      "Missing risks",
      "Compliance gaps",
    ],
    aiCapabilities: ["Risk Modeling", "Predictive Analytics", "Pattern Recognition"],
    solutions: ["Credit Scoring", "Insurance Underwriting", "Compliance Monitoring", "Vendor Assessment"],
    metrics: {
      assessmentSpeed: "90% faster",
      accuracy: "95%",
      riskDetection: "+40%",
    },
  },
  {
    slug: "compliance",
    name: "Compliance Automation",
    description: "Ensure regulatory compliance automatically",
    painPoints: [
      "Regulatory changes",
      "Manual monitoring",
      "Audit preparation",
      "Documentation burden",
      "Violation risks",
    ],
    aiCapabilities: ["Rule Engines", "Document Analysis", "Monitoring Systems"],
    solutions: ["Compliance Monitoring", "Audit Automation", "Policy Management", "Reporting Tools"],
    metrics: {
      complianceRate: "99%",
      auditTime: "-70%",
      violations: "-80%",
    },
  },
  {
    slug: "lead-generation",
    name: "Lead Generation",
    description: "Identify and qualify leads automatically",
    painPoints: [
      "Lead quality",
      "Manual qualification",
      "Conversion rates",
      "Follow-up timing",
      "Lead scoring",
    ],
    aiCapabilities: ["Predictive Scoring", "Intent Analysis", "Behavioral Tracking"],
    solutions: ["Lead Scoring", "Intent Detection", "Automated Outreach", "Conversion Prediction"],
    metrics: {
      leadQuality: "+60%",
      conversionRate: "+40%",
      salesCycle: "-25%",
    },
  },
  {
    slug: "process-automation",
    name: "Process Automation",
    description: "Automate repetitive business processes",
    painPoints: [
      "Manual workflows",
      "Process errors",
      "Slow execution",
      "Resource waste",
      "Scalability limits",
    ],
    aiCapabilities: ["RPA", "Workflow Automation", "Decision Trees"],
    solutions: ["Workflow Automation", "Task Bots", "Process Mining", "Integration Automation"],
    metrics: {
      processTime: "-75%",
      errorRate: "-90%",
      cost: "-60%",
    },
  },
  {
    slug: "decision-support",
    name: "Decision Support",
    description: "Augment human decision-making with AI",
    painPoints: [
      "Complex decisions",
      "Information overload",
      "Decision speed",
      "Consistency needs",
      "Risk visibility",
    ],
    aiCapabilities: ["Decision Trees", "Scenario Analysis", "Recommendation Systems"],
    solutions: ["Decision Engines", "Scenario Planning", "Risk Analysis", "Recommendation Systems"],
    metrics: {
      decisionSpeed: "5x faster",
      accuracy: "+30%",
      consistency: "95%",
    },
  },
  {
    slug: "knowledge-management",
    name: "Knowledge Management",
    description: "Organize and retrieve knowledge efficiently",
    painPoints: [
      "Information silos",
      "Search inefficiency",
      "Knowledge gaps",
      "Onboarding time",
      "Expertise location",
    ],
    aiCapabilities: ["Knowledge Graphs", "Semantic Search", "Information Extraction"],
    solutions: ["Knowledge Base AI", "Expert Systems", "Smart Search", "FAQ Automation"],
    metrics: {
      searchTime: "-80%",
      knowledgeAccess: "+90%",
      onboarding: "-50%",
    },
  },
];

export type Problem = typeof PROBLEMS[0];