export const AI_SOLUTIONS = [
  {
    slug: "chatbots",
    name: "AI Chatbots & Virtual Assistants",
    description: "24/7 intelligent customer engagement",
    features: [
      "Natural language understanding",
      "Multi-language support",
      "Context retention",
      "Sentiment analysis",
      "Integration with CRM",
    ],
    useCases: ["Customer support", "Lead qualification", "FAQ automation", "Order tracking"],
    technologies: ["GPT-5", "Claude", "Custom NLP models"],
    pricing: "Starting at $2,000/month",
  },
  {
    slug: "predictive-analytics",
    name: "Predictive Analytics Platform",
    description: "Forecast trends and optimize decisions",
    features: [
      "Time series forecasting",
      "Trend analysis",
      "Anomaly detection",
      "Custom dashboards",
      "Real-time alerts",
    ],
    useCases: ["Sales forecasting", "Demand planning", "Risk prediction", "Churn analysis"],
    technologies: ["Machine Learning", "Statistical Models", "Deep Learning"],
    pricing: "Starting at $5,000/month",
  },
  {
    slug: "document-intelligence",
    name: "Document Intelligence System",
    description: "Extract and process documents automatically",
    features: [
      "OCR and text extraction",
      "Form processing",
      "Contract analysis",
      "Data validation",
      "Multi-format support",
    ],
    useCases: ["Invoice processing", "Contract review", "Form automation", "Compliance docs"],
    technologies: ["Computer Vision", "NLP", "Pattern Recognition"],
    pricing: "Starting at $3,000/month",
  },
  {
    slug: "recommendation-engine",
    name: "AI Recommendation Engine",
    description: "Personalize experiences at scale",
    features: [
      "Collaborative filtering",
      "Content-based recommendations",
      "Real-time personalization",
      "A/B testing",
      "Cross-sell optimization",
    ],
    useCases: ["Product recommendations", "Content curation", "Next best action", "Upselling"],
    technologies: ["Deep Learning", "Graph Neural Networks", "Reinforcement Learning"],
    pricing: "Starting at $4,000/month",
  },
  {
    slug: "fraud-detection-system",
    name: "Fraud Detection System",
    description: "Real-time fraud prevention and detection",
    features: [
      "Transaction monitoring",
      "Pattern recognition",
      "Risk scoring",
      "Alert management",
      "Investigation tools",
    ],
    useCases: ["Payment fraud", "Account takeover", "Identity verification", "Claims fraud"],
    technologies: ["Anomaly Detection", "Neural Networks", "Behavioral Analysis"],
    pricing: "Starting at $10,000/month",
  },
  {
    slug: "computer-vision",
    name: "Computer Vision Solutions",
    description: "Visual AI for quality and safety",
    features: [
      "Object detection",
      "Quality inspection",
      "Facial recognition",
      "Video analytics",
      "Real-time processing",
    ],
    useCases: ["Quality control", "Security monitoring", "Inventory tracking", "Safety compliance"],
    technologies: ["CNNs", "YOLO", "Vision Transformers"],
    pricing: "Starting at $7,000/month",
  },
  {
    slug: "workflow-automation",
    name: "Intelligent Process Automation",
    description: "End-to-end workflow automation",
    features: [
      "Process mining",
      "Task automation",
      "Decision logic",
      "Integration hub",
      "Exception handling",
    ],
    useCases: ["Order processing", "HR workflows", "Finance operations", "IT automation"],
    technologies: ["RPA", "Process Mining", "Decision Trees"],
    pricing: "Starting at $5,000/month",
  },
  {
    slug: "sentiment-analysis",
    name: "Sentiment Analysis Platform",
    description: "Understand customer emotions at scale",
    features: [
      "Text sentiment analysis",
      "Voice emotion detection",
      "Social media monitoring",
      "Review analysis",
      "Trend tracking",
    ],
    useCases: ["Brand monitoring", "Customer feedback", "Market research", "Product reviews"],
    technologies: ["NLP", "Deep Learning", "Transformers"],
    pricing: "Starting at $2,500/month",
  },
  {
    slug: "voice-analytics",
    name: "Voice Analytics & Transcription",
    description: "Transform voice into actionable insights",
    features: [
      "Speech-to-text",
      "Speaker identification",
      "Emotion detection",
      "Call analytics",
      "Compliance monitoring",
    ],
    useCases: ["Call center analytics", "Meeting transcription", "Voice commands", "Compliance"],
    technologies: ["Speech Recognition", "Audio Processing", "NLP"],
    pricing: "Starting at $3,500/month",
  },
  {
    slug: "knowledge-base-ai",
    name: "AI Knowledge Base",
    description: "Intelligent knowledge management",
    features: [
      "Semantic search",
      "Auto-categorization",
      "Content generation",
      "Expert location",
      "Q&A automation",
    ],
    useCases: ["Documentation", "Employee training", "Customer self-service", "Expert systems"],
    technologies: ["Knowledge Graphs", "Vector Databases", "LLMs"],
    pricing: "Starting at $3,000/month",
  },
  {
    slug: "demand-forecasting",
    name: "Demand Forecasting AI",
    description: "Accurate demand prediction",
    features: [
      "Multi-factor analysis",
      "Seasonal adjustments",
      "External data integration",
      "Scenario planning",
      "Inventory optimization",
    ],
    useCases: ["Retail planning", "Supply chain", "Resource allocation", "Capacity planning"],
    technologies: ["Time Series ML", "LSTM Networks", "Prophet"],
    pricing: "Starting at $6,000/month",
  },
  {
    slug: "content-generation",
    name: "AI Content Generation",
    description: "Create content at scale",
    features: [
      "Blog writing",
      "Product descriptions",
      "Social media posts",
      "Email templates",
      "SEO optimization",
    ],
    useCases: ["Marketing content", "Product catalogs", "Documentation", "Social media"],
    technologies: ["GPT-5", "Claude", "Fine-tuned Models"],
    pricing: "Starting at $1,500/month",
  },
  {
    slug: "risk-scoring",
    name: "AI Risk Scoring Models",
    description: "Automated risk assessment",
    features: [
      "Credit scoring",
      "Underwriting automation",
      "Portfolio risk analysis",
      "Compliance scoring",
      "Vendor assessment",
    ],
    useCases: ["Lending", "Insurance", "Investment", "Vendor management"],
    technologies: ["Gradient Boosting", "Neural Networks", "Ensemble Models"],
    pricing: "Starting at $8,000/month",
  },
  {
    slug: "optimization-algorithms",
    name: "Optimization Algorithms",
    description: "Solve complex optimization problems",
    features: [
      "Route optimization",
      "Resource allocation",
      "Scheduling optimization",
      "Price optimization",
      "Portfolio optimization",
    ],
    useCases: ["Logistics", "Workforce management", "Pricing", "Investment"],
    technologies: ["Genetic Algorithms", "Linear Programming", "Reinforcement Learning"],
    pricing: "Starting at $7,500/month",
  },
  {
    slug: "anomaly-detection",
    name: "Anomaly Detection System",
    description: "Identify outliers and unusual patterns",
    features: [
      "Real-time detection",
      "Multi-dimensional analysis",
      "Adaptive thresholds",
      "Root cause analysis",
      "Alert prioritization",
    ],
    useCases: ["Security monitoring", "Quality control", "Network monitoring", "Fraud detection"],
    technologies: ["Isolation Forest", "Autoencoders", "Statistical Methods"],
    pricing: "Starting at $4,500/month",
  },
];

export type AISolution = typeof AI_SOLUTIONS[0];

export const LOCATIONS = [
  { slug: "san-francisco-ca", city: "San Francisco", state: "California", region: "West Coast" },
  { slug: "new-york-ny", city: "New York", state: "New York", region: "East Coast" },
  { slug: "austin-tx", city: "Austin", state: "Texas", region: "South" },
  { slug: "seattle-wa", city: "Seattle", state: "Washington", region: "Pacific Northwest" },
  { slug: "boston-ma", city: "Boston", state: "Massachusetts", region: "Northeast" },
  { slug: "chicago-il", city: "Chicago", state: "Illinois", region: "Midwest" },
  { slug: "los-angeles-ca", city: "Los Angeles", state: "California", region: "West Coast" },
  { slug: "miami-fl", city: "Miami", state: "Florida", region: "Southeast" },
  { slug: "denver-co", city: "Denver", state: "Colorado", region: "Mountain West" },
  { slug: "atlanta-ga", city: "Atlanta", state: "Georgia", region: "Southeast" },
  { slug: "dallas-tx", city: "Dallas", state: "Texas", region: "South" },
  { slug: "phoenix-az", city: "Phoenix", state: "Arizona", region: "Southwest" },
  { slug: "philadelphia-pa", city: "Philadelphia", state: "Pennsylvania", region: "Northeast" },
  { slug: "washington-dc", city: "Washington", state: "DC", region: "Mid-Atlantic" },
  { slug: "detroit-mi", city: "Detroit", state: "Michigan", region: "Midwest" },
  { slug: "minneapolis-mn", city: "Minneapolis", state: "Minnesota", region: "Upper Midwest" },
  { slug: "san-diego-ca", city: "San Diego", state: "California", region: "West Coast" },
  { slug: "portland-or", city: "Portland", state: "Oregon", region: "Pacific Northwest" },
  { slug: "nashville-tn", city: "Nashville", state: "Tennessee", region: "Southeast" },
  { slug: "charlotte-nc", city: "Charlotte", state: "North Carolina", region: "Southeast" },
];

export type Location = typeof LOCATIONS[0];