// PDF Generator utility for creating proposal PDFs
// Using a simplified approach for now - can be enhanced with @react-pdf/renderer later

export class PDFDocument {
  private content: string[] = []
  private metadata: Record<string, unknown>
  
  constructor(metadata: Record<string, unknown>) {
    this.metadata = metadata
  }

  addCoverPage(data: {
    title: string
    subtitle?: string
    client: string
    company?: string
    date: string
  }) {
    this.content.push(`
# ${data.title}

## ${data.subtitle || ''}

Prepared for: **${data.client}**
${data.company ? `Company: **${data.company}**` : ''}

Date: ${data.date}

---
    `)
  }

  addSection(data: {
    title: string
    type: string
    content: unknown
    pageBreak?: boolean
  }) {
    if (data.pageBreak) {
      this.content.push('\n\n---\n\n')
    }
    
    this.content.push(`## ${data.title}\n\n`)
    
    if (data.type === 'text') {
      this.content.push(`${this.formatContent(data.content)}\n\n`)
    } else if (data.type === 'list') {
      const items = Array.isArray(data.content) ? data.content : []
      items.forEach((item) => {
        this.content.push(`- ${String(item)}\n`)
      })
      this.content.push('\n')
    } else if (data.type === 'timeline') {
      this.content.push(this.formatTimeline(data.content))
    } else if (data.type === 'pricing') {
      this.content.push(this.formatPricing(data.content))
    } else {
      this.content.push(`${JSON.stringify(data.content, null, 2)}\n\n`)
    }
  }

  private formatContent(content: unknown): string {
    if (typeof content === 'string') {
      return content
    }
    if (typeof content === 'object' && content !== null) {
      return Object.entries(content)
        .map(([key, value]) => `**${key}:** ${value}`)
        .join('\n')
    }
    return String(content)
  }

  private formatTimeline(timeline: unknown): string {
    const tl = timeline as {
      duration?: string
      milestones?: Array<{
        title: string
        timing?: string
        date?: string
        description: string
      }>
    }
    let result = ''
    if (tl.duration) {
      result += `**Duration:** ${tl.duration}\n\n`
    }
    if (tl.milestones) {
      result += '### Milestones\n\n'
      tl.milestones.forEach((milestone, index) => {
        result += `**${index + 1}. ${milestone.title}**\n`
        result += `*${milestone.timing || milestone.date || ''}*\n`
        result += `${milestone.description}\n\n`
      })
    }
    return result
  }

  private formatPricing(pricing: unknown): string {
    const pr = pricing as {
      totalPrice?: string
      total?: number
      structure?: string
      paymentTerms?: string
      schedule?: Array<{
        milestone: string
        percentage: number
      }>
    }
    let result = ''
    if (pr.totalPrice || pr.total) {
      result += `### Total Investment\n\n**${pr.totalPrice || pr.total}**\n\n`
    }
    if (pr.structure) {
      result += `**Structure:** ${pr.structure}\n\n`
    }
    if (pr.paymentTerms) {
      result += `**Payment Terms:** ${pr.paymentTerms}\n\n`
    }
    if (pr.schedule) {
      result += '### Payment Schedule\n\n'
      pr.schedule.forEach((payment) => {
        result += `- ${payment.milestone}: ${payment.percentage}%\n`
      })
      result += '\n'
    }
    return result
  }

  addFooter() {
    this.content.push(`\n\n---\n\n*${this.metadata.title || 'Proposal'} | Generated by Sprinter AI*\n`)
  }

  async generate(): Promise<Buffer> {
    // For now, return the markdown content as a buffer
    // In production, this would use a proper PDF library
    const markdown = this.content.join('')
    return Buffer.from(markdown, 'utf-8')
  }
}

// Simple markdown to HTML converter for basic formatting
export function markdownToHtml(markdown: string): string {
  return markdown
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/\*\*(.*)\\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gim, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/g, '<ul>$1</ul>')
    .replace(/\n\n/g, '<br><br>')
    .replace(/\n/g, '<br>')
}