"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  SparklesIcon,
  BuildingOfficeIcon,
  ChartBarIcon,
  LightBulbIcon,
  RocketLaunchIcon,
  DocumentTextIcon,
  ArrowRightIcon,
  CheckCircleIcon,
  ClockIcon,
  CurrencyDollarIcon,
} from "@heroicons/react/24/outline";
import { generateIndustryBlueprint } from "./actions";

interface BlueprintSection {
  title: string;
  items: string[];
}

interface Blueprint {
  industry: string;
  overview: string;
  opportunities: BlueprintSection;
  useCases: BlueprintSection;
  implementation: BlueprintSection;
  vendors: BlueprintSection;
  roi: {
    efficiency: string;
    revenue: string;
    timeline: string;
  };
}

const industryExamples = [
  "Private Equity",
  "Healthcare",
  "Manufacturing",
  "Retail & E-commerce",
  "Financial Services",
  "Real Estate",
  "Logistics",
  "Professional Services",
];

export default function IndustryBlueprintPage() {
  const [industry, setIndustry] = useState("");
  const [companySize, setCompanySize] = useState("mid-market");
  const [focusArea, setFocusArea] = useState("efficiency");
  const [isGenerating, setIsGenerating] = useState(false);
  const [blueprint, setBlueprint] = useState<Blueprint | null>(null);

  const handleGenerate = async () => {
    if (!industry.trim()) return;

    setIsGenerating(true);
    try {
      const result = await generateIndustryBlueprint({
        industry,
        companySize,
        focusArea,
      });
      setBlueprint(result);
    } catch (error) {
      console.error("Error generating blueprint:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!blueprint) return;

    // Create a text version of the blueprint
    const content = `
AI TRANSFORMATION BLUEPRINT
${blueprint.industry.toUpperCase()}
Generated by Sprinter AI

OVERVIEW
${blueprint.overview}

KEY OPPORTUNITIES
${blueprint.opportunities.items.map(item => `• ${item}`).join('\n')}

USE CASES
${blueprint.useCases.items.map(item => `• ${item}`).join('\n')}

IMPLEMENTATION ROADMAP
${blueprint.implementation.items.map(item => `• ${item}`).join('\n')}

RECOMMENDED VENDORS & TOOLS
${blueprint.vendors.items.map(item => `• ${item}`).join('\n')}

ROI PROJECTIONS
• Efficiency Gains: ${blueprint.roi.efficiency}
• Revenue Impact: ${blueprint.roi.revenue}
• Time to Value: ${blueprint.roi.timeline}

---
Ready to accelerate your AI transformation?
Contact Sprinter AI at hello@sprinter.tech
`;

    // Create and trigger download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai-blueprint-${industry.toLowerCase().replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen py-24">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-12">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-blue-500/10 to-purple-500/10 border border-blue-500/20 mb-6"
          >
            <SparklesIcon className="w-5 h-5 text-blue-400" />
            <span className="text-sm font-medium">AI Strategy Generator</span>
          </motion.div>

          <h1 className="text-5xl font-bold mb-4">
            AI Industry <span className="gradient-text">Blueprint</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Generate a comprehensive AI transformation blueprint for any industry
            in seconds. Get specific use cases, vendors, and ROI projections.
          </p>
        </div>

        {/* Input Form */}
        {!blueprint && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="max-w-2xl mx-auto mb-12"
          >
            <div className="bg-card/50 backdrop-blur-xl rounded-2xl border border-border/50 p-8">
              {/* Industry Input */}
              <div className="mb-6">
                <label className="block text-sm font-medium mb-2">
                  Industry or Sector
                </label>
                <input
                  type="text"
                  value={industry}
                  onChange={(e) => setIndustry(e.target.value)}
                  placeholder="e.g., Private Equity, Healthcare, Manufacturing..."
                  className="w-full px-4 py-3 rounded-xl bg-background/50 border border-border focus:border-blue-400 focus:outline-none transition-colors"
                />
                <div className="flex flex-wrap gap-2 mt-3">
                  {industryExamples.map((example) => (
                    <button
                      key={example}
                      onClick={() => setIndustry(example)}
                      className="px-3 py-1 rounded-full text-xs bg-white/5 hover:bg-white/10 transition-colors"
                    >
                      {example}
                    </button>
                  ))}
                </div>
              </div>

              {/* Company Size */}
              <div className="mb-6">
                <label className="block text-sm font-medium mb-2">
                  Company Size
                </label>
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { value: "startup", label: "Startup", range: "<50 employees" },
                    { value: "mid-market", label: "Mid-Market", range: "50-500" },
                    { value: "enterprise", label: "Enterprise", range: "500+" },
                  ].map((size) => (
                    <button
                      key={size.value}
                      onClick={() => setCompanySize(size.value)}
                      className={`p-3 rounded-xl border transition-all ${
                        companySize === size.value
                          ? "bg-blue-500/20 border-blue-400 text-blue-400"
                          : "bg-background/50 border-border hover:border-white/30"
                      }`}
                    >
                      <div className="font-medium">{size.label}</div>
                      <div className="text-xs text-muted-foreground mt-1">
                        {size.range}
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Focus Area */}
              <div className="mb-8">
                <label className="block text-sm font-medium mb-2">
                  Primary Focus
                </label>
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { value: "efficiency", label: "Operational Efficiency", icon: ChartBarIcon },
                    { value: "growth", label: "Revenue Growth", icon: RocketLaunchIcon },
                    { value: "innovation", label: "Product Innovation", icon: LightBulbIcon },
                    { value: "experience", label: "Customer Experience", icon: BuildingOfficeIcon },
                  ].map((focus) => (
                    <button
                      key={focus.value}
                      onClick={() => setFocusArea(focus.value)}
                      className={`p-4 rounded-xl border transition-all flex items-center gap-3 ${
                        focusArea === focus.value
                          ? "bg-purple-500/20 border-purple-400 text-purple-400"
                          : "bg-background/50 border-border hover:border-white/30"
                      }`}
                    >
                      <focus.icon className="w-5 h-5" />
                      <span className="font-medium">{focus.label}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Generate Button */}
              <button
                onClick={handleGenerate}
                disabled={!industry.trim() || isGenerating}
                className="w-full py-4 rounded-xl bg-gradient-to-r from-blue-500 to-purple-500 text-white font-semibold disabled:opacity-50 hover:opacity-90 transition-opacity flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Generating Blueprint...
                  </>
                ) : (
                  <>
                    <SparklesIcon className="w-5 h-5" />
                    Generate AI Blueprint
                  </>
                )}
              </button>
            </div>
          </motion.div>
        )}

        {/* Generated Blueprint */}
        <AnimatePresence>
          {blueprint && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-6xl mx-auto"
            >
              {/* Blueprint Header */}
              <div className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 rounded-2xl border border-blue-500/20 p-8 mb-8">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h2 className="text-3xl font-bold mb-2">
                      {blueprint.industry} AI Transformation Blueprint
                    </h2>
                    <p className="text-muted-foreground">
                      {blueprint.overview}
                    </p>
                  </div>
                  <button
                    onClick={handleDownload}
                    className="px-4 py-2 rounded-lg bg-white/10 hover:bg-white/20 transition-colors flex items-center gap-2"
                  >
                    <DocumentTextIcon className="w-5 h-5" />
                    Download
                  </button>
                </div>

                {/* ROI Summary */}
                <div className="grid grid-cols-3 gap-4 mt-6">
                  <div className="bg-black/20 rounded-xl p-4">
                    <div className="flex items-center gap-2 text-green-400 mb-2">
                      <ChartBarIcon className="w-5 h-5" />
                      <span className="text-sm font-medium">Efficiency</span>
                    </div>
                    <div className="text-2xl font-bold">{blueprint.roi.efficiency}</div>
                  </div>
                  <div className="bg-black/20 rounded-xl p-4">
                    <div className="flex items-center gap-2 text-blue-400 mb-2">
                      <CurrencyDollarIcon className="w-5 h-5" />
                      <span className="text-sm font-medium">Revenue</span>
                    </div>
                    <div className="text-2xl font-bold">{blueprint.roi.revenue}</div>
                  </div>
                  <div className="bg-black/20 rounded-xl p-4">
                    <div className="flex items-center gap-2 text-purple-400 mb-2">
                      <ClockIcon className="w-5 h-5" />
                      <span className="text-sm font-medium">Timeline</span>
                    </div>
                    <div className="text-2xl font-bold">{blueprint.roi.timeline}</div>
                  </div>
                </div>
              </div>

              {/* Blueprint Sections */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Opportunities */}
                <div className="bg-card/50 backdrop-blur-xl rounded-xl border border-border/50 p-6">
                  <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <LightBulbIcon className="w-6 h-6 text-yellow-400" />
                    {blueprint.opportunities.title}
                  </h3>
                  <ul className="space-y-3">
                    {blueprint.opportunities.items.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                        <CheckCircleIcon className="w-5 h-5 text-green-400 mt-0.5 flex-shrink-0" />
                        <span className="text-sm">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Use Cases */}
                <div className="bg-card/50 backdrop-blur-xl rounded-xl border border-border/50 p-6">
                  <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <RocketLaunchIcon className="w-6 h-6 text-blue-400" />
                    {blueprint.useCases.title}
                  </h3>
                  <ul className="space-y-3">
                    {blueprint.useCases.items.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                        <ArrowRightIcon className="w-5 h-5 text-blue-400 mt-0.5 flex-shrink-0" />
                        <span className="text-sm">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Implementation */}
                <div className="bg-card/50 backdrop-blur-xl rounded-xl border border-border/50 p-6">
                  <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <ChartBarIcon className="w-6 h-6 text-purple-400" />
                    {blueprint.implementation.title}
                  </h3>
                  <ul className="space-y-3">
                    {blueprint.implementation.items.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                        <span className="text-purple-400 font-bold">{idx + 1}.</span>
                        <span className="text-sm">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Vendors */}
                <div className="bg-card/50 backdrop-blur-xl rounded-xl border border-border/50 p-6">
                  <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                    <BuildingOfficeIcon className="w-6 h-6 text-orange-400" />
                    {blueprint.vendors.title}
                  </h3>
                  <ul className="space-y-3">
                    {blueprint.vendors.items.map((item, idx) => (
                      <li key={idx} className="flex items-start gap-3">
                        <CheckCircleIcon className="w-5 h-5 text-orange-400 mt-0.5 flex-shrink-0" />
                        <span className="text-sm">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* CTA */}
              <div className="mt-12 text-center p-8 rounded-2xl bg-gradient-to-r from-blue-500/10 to-purple-500/10 border border-blue-500/20">
                <h3 className="text-2xl font-bold mb-4">
                  Ready to Transform Your {blueprint.industry} Business?
                </h3>
                <p className="text-muted-foreground mb-6">
                  Let's turn this blueprint into reality. Our AI experts will help you
                  implement these solutions with guaranteed ROI.
                </p>
                <div className="flex gap-4 justify-center">
                  <button
                    onClick={() => {
                      setBlueprint(null);
                      setIndustry("");
                    }}
                    className="px-6 py-3 rounded-xl bg-white/10 hover:bg-white/20 transition-colors"
                  >
                    Generate Another
                  </button>
                  <a
                    href="/contact"
                    className="px-6 py-3 rounded-xl bg-gradient-to-r from-blue-500 to-purple-500 text-white font-semibold hover:opacity-90 transition-opacity"
                  >
                    Get Expert Help
                  </a>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}